name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: devRenanPaulino
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit snake files
        run: |
          mkdir -p output
          mv dist/*.svg output/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A output
          git commit -m "chore: update snake 🐍" || echo "No changes"
          git push origin HEAD:output
